@baseUrl = http://localhost:8080/api

### -----------------------
### HEALTH CHECK
### -----------------------

### Cek Status Server
GET http://localhost:8080/health

### -----------------------
### MODULE: CATEGORY
### -----------------------

### 1. Get All Categories
GET {{baseUrl}}/category
Content-Type: application/json

### 2. Get Category By ID
GET {{baseUrl}}/category/1
Content-Type: application/json

### 3. Create New Category
POST {{baseUrl}}/category
Content-Type: application/json

{
    "nama": "Elektronik",
    "deskripsi": "Gadget dan alat listrik"
}

### 4. Update Category (Ganti ID sesuai kebutuhan)
PUT {{baseUrl}}/category/1
Content-Type: application/json

{
    "nama": "Makanan Berat",
    "deskripsi": "Nasi dan lauk pauk"
}

### 5. Delete Category
DELETE {{baseUrl}}/category/3
Content-Type: application/json

### -----------------------
### MODULE: PRODUK
### -----------------------

### 1. Get All Produk
GET {{baseUrl}}/produk
Content-Type: application/json

### 2. Get Produk By ID
GET {{baseUrl}}/produk/1
Content-Type: application/json

### 3. Create New Produk
POST {{baseUrl}}/produk
Content-Type: application/json

{
    "nama": "Teh Pucuk Harum",
    "harga": 4000,
    "stok": 50
}

### 4. Update Produk
PUT {{baseUrl}}/produk/2
Content-Type: application/json

{
    "nama": "Vit 600ml (Update)",
    "harga": 2500,
    "stok": 35
}

### 5. Delete Produk
DELETE {{baseUrl}}/produk/3
Content-Type: application/json